/**
 * Transcripts.
 *
 * These need no API key, no OAuth, and no quota. YouTube serves caption tracks
 * to the watch page itself, and that is what we read. It is the only part of
 * this server that works the moment it is installed.
 *
 * The trade is that it is not a supported API. YouTube changes the watch page
 * shape occasionally and this has to follow. Everything here is written to fail
 * as "no transcript" rather than to throw, because a missing transcript is a
 * normal outcome: plenty of videos genuinely have no captions.
 *
 * Do not confuse this with the Captions API (`captions.download`), which the
 * account tools use. That one needs OAuth AND channel ownership, so it can only
 * ever read your own videos. This reads anyone's.
 */

import { fetchCaptions, YtDlpMissingError } from "./ytdlp.js";

const WATCH_URL = "https://www.youtube.com/watch";

// Without a browser-ish UA, YouTube serves a consent interstitial with no
// player response in it, and every video looks like it has no captions.
const HEADERS = {
  "User-Agent":
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36",
  "Accept-Language": "en-US,en;q=0.9",
};

export type TranscriptSegment = {
  /** Seconds from the start of the video. */
  start: number;
  /** Segment duration in seconds. */
  duration: number;
  text: string;
};

export type TranscriptTrack = {
  languageCode: string;
  languageName: string;
  /** True when YouTube generated these captions rather than a human writing them. */
  autoGenerated: boolean;
  url: string;
};

export class TranscriptError extends Error {
  constructor(
    message: string,
    readonly code:
      | "no_video"
      | "no_captions"
      | "language_missing"
      | "blocked"
      | "rate_limited"
      | "no_ytdlp"
      | "network",
  ) {
    super(message);
    this.name = "TranscriptError";
  }
}

/**
 * Accepts anything a user is likely to paste: a bare id, a watch URL, a
 * youtu.be link, a Shorts URL, an embed, or a live URL.
 */
export function parseVideoId(input: string): string | null {
  const raw = (input || "").trim();
  if (!raw) return null;

  // A bare id. YouTube ids are 11 chars of [A-Za-z0-9_-].
  if (/^[\w-]{11}$/.test(raw)) return raw;

  let url: URL;
  try {
    url = new URL(raw.startsWith("http") ? raw : `https://${raw}`);
  } catch {
    return null;
  }

  if (url.hostname.endsWith("youtu.be")) {
    const id = url.pathname.slice(1).split("/")[0];
    return id && /^[\w-]{11}$/.test(id) ? id : null;
  }

  const v = url.searchParams.get("v");
  if (v && /^[\w-]{11}$/.test(v)) return v;

  const m = url.pathname.match(/\/(shorts|embed|live|v)\/([\w-]{11})/);
  return m?.[2] ?? null;
}

/** Decode the XML entities YouTube puts in caption text, including the double-escaped ones. */
function decodeEntities(text: string): string {
  return text
    .replace(/&amp;#(\d+);/g, (_, code: string) => String.fromCharCode(Number(code)))
    .replace(/&#(\d+);/g, (_, code: string) => String.fromCharCode(Number(code)))
    .replace(/&amp;quot;/g, '"')
    .replace(/&quot;/g, '"')
    .replace(/&amp;#39;/g, "'")
    .replace(/&#39;/g, "'")
    .replace(/&amp;lt;/g, "<")
    .replace(/&lt;/g, "<")
    .replace(/&amp;gt;/g, ">")
    .replace(/&gt;/g, ">")
    .replace(/&amp;nbsp;/g, " ")
    .replace(/&nbsp;/g, " ")
    .replace(/&amp;/g, "&")
    .trim();
}

async function fetchText(url: string, timeoutMs: number): Promise<string> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    const res = await fetch(url, { headers: HEADERS, signal: controller.signal });
    if (res.status === 429) {
      throw new TranscriptError(
        "YouTube is rate limiting transcript requests from this IP. Wait a few minutes, or retry from another network.",
        "rate_limited",
      );
    }
    if (!res.ok) {
      throw new TranscriptError(`YouTube returned ${res.status} for ${url}`, "network");
    }
    return await res.text();
  } catch (err) {
    if (err instanceof TranscriptError) throw err;
    if (err instanceof Error && err.name === "AbortError") {
      throw new TranscriptError(`Timed out after ${timeoutMs}ms fetching the transcript.`, "network");
    }
    throw new TranscriptError(err instanceof Error ? err.message : String(err), "network");
  } finally {
    clearTimeout(timer);
  }
}

/**
 * Pull the caption track list out of the watch page.
 *
 * The player response is embedded in the HTML as a JSON blob. We locate it by
 * its key and balance braces rather than regex the whole object, because the
 * blob contains nested braces inside strings and a greedy regex reliably
 * grabs either too little or the rest of the document.
 */
function extractPlayerResponse(html: string): Record<string, unknown> | null {
  const key = "ytInitialPlayerResponse";
  const at = html.indexOf(key);
  if (at === -1) return null;
  const braceStart = html.indexOf("{", at);
  if (braceStart === -1) return null;

  let depth = 0;
  let inString = false;
  let escaped = false;
  for (let i = braceStart; i < html.length; i++) {
    const ch = html[i];
    if (escaped) {
      escaped = false;
      continue;
    }
    if (ch === "\\") {
      escaped = true;
      continue;
    }
    if (ch === '"') {
      inString = !inString;
      continue;
    }
    if (inString) continue;
    if (ch === "{") depth++;
    else if (ch === "}") {
      depth--;
      if (depth === 0) {
        try {
          return JSON.parse(html.slice(braceStart, i + 1)) as Record<string, unknown>;
        } catch {
          return null;
        }
      }
    }
  }
  return null;
}

/** Every caption track YouTube will serve for this video. */
export async function listTracks(
  videoId: string,
  timeoutMs = 15000,
): Promise<TranscriptTrack[]> {
  const html = await fetchText(`${WATCH_URL}?v=${videoId}&hl=en`, timeoutMs);
  const player = extractPlayerResponse(html);
  if (!player) {
    throw new TranscriptError(
      "Could not read the video page. The video may be private, deleted, or age-restricted.",
      "no_video",
    );
  }

  const status = (player.playabilityStatus as { status?: string } | undefined)?.status;
  if (status && status !== "OK") {
    throw new TranscriptError(
      `YouTube will not play this video (${status}). Private, deleted, or region-locked videos have no readable transcript.`,
      "no_video",
    );
  }

  const captions = player.captions as
    | { playerCaptionsTracklistRenderer?: { captionTracks?: unknown[] } }
    | undefined;
  const tracks = captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [];

  return (tracks as Record<string, unknown>[])
    .map((t) => ({
      languageCode: String(t.languageCode ?? ""),
      languageName: String(
        (t.name as { simpleText?: string; runs?: { text?: string }[] } | undefined)?.simpleText ??
          (t.name as { runs?: { text?: string }[] } | undefined)?.runs?.[0]?.text ??
          t.languageCode ??
          "",
      ),
      // `asr` = automatic speech recognition, i.e. YouTube's own auto-captions.
      autoGenerated: String(t.kind ?? "") === "asr",
      url: String(t.baseUrl ?? ""),
    }))
    .filter((t) => t.url);
}

/**
 * Pick a track for the requested language.
 *
 * Preference order, and the reason for it: an exact match first; then the same
 * language ignoring region, so `en` finds `en-GB`; then a human-written track
 * in any language, which beats auto-captions on accuracy; then whatever exists.
 */
function pickTrack(tracks: TranscriptTrack[], language?: string): TranscriptTrack | null {
  if (tracks.length === 0) return null;
  if (!language) {
    return tracks.find((t) => !t.autoGenerated) ?? tracks[0] ?? null;
  }
  const want = language.toLowerCase();
  return (
    tracks.find((t) => t.languageCode.toLowerCase() === want) ??
    tracks.find((t) => t.languageCode.toLowerCase().split("-")[0] === want.split("-")[0]) ??
    null
  );
}

function parseTimedText(xml: string): TranscriptSegment[] {
  const out: TranscriptSegment[] = [];
  const re = /<text([^>]*)>([\s\S]*?)<\/text>/g;
  let m: RegExpExecArray | null;
  while ((m = re.exec(xml)) !== null) {
    const attrs = m[1] ?? "";
    const body = m[2] ?? "";
    const start = Number(/\bstart="([\d.]+)"/.exec(attrs)?.[1] ?? 0);
    const duration = Number(/\bdur="([\d.]+)"/.exec(attrs)?.[1] ?? 0);
    const text = decodeEntities(body.replace(/<[^>]+>/g, ""));
    if (text) out.push({ start, duration, text });
  }
  return out;
}

export type FetchTranscriptOptions = {
  language?: string;
  timeoutMs?: number;
};

export type Transcript = {
  videoId: string;
  language: string;
  autoGenerated: boolean;
  segments: TranscriptSegment[];
};

/** Fetch one video's transcript. Throws TranscriptError with a `code` you can branch on. */
export async function fetchTranscript(
  videoIdOrUrl: string,
  opts: FetchTranscriptOptions = {},
): Promise<Transcript> {
  const videoId = parseVideoId(videoIdOrUrl);
  if (!videoId) {
    throw new TranscriptError(
      `Could not read a video id out of "${videoIdOrUrl}". Pass a video id or a YouTube URL.`,
      "no_video",
    );
  }
  const timeoutMs = opts.timeoutMs ?? 15000;

  const tracks = await listTracks(videoId, timeoutMs);
  if (tracks.length === 0) {
    throw new TranscriptError(
      "This video has no captions at all, so there is no transcript to read.",
      "no_captions",
    );
  }

  const track = pickTrack(tracks, opts.language);
  if (!track) {
    const available = tracks.map((t) => t.languageCode).join(", ");
    throw new TranscriptError(
      `No "${opts.language}" captions on this video. Available: ${available}.`,
      "language_missing",
    );
  }

  // The track list above is real, but YouTube answers the track URL itself with
  // an empty body unless the request carries a proof-of-origin token. yt-dlp
  // mints one, so the body comes from there while the list comes from the page.
  let segments: TranscriptSegment[];
  let language = track.languageCode;
  let autoGenerated = track.autoGenerated;
  try {
    const viaYtDlp = await fetchCaptions(videoId, track.languageCode, Math.max(timeoutMs, 90000));
    segments = viaYtDlp.segments;
    language = viaYtDlp.language;
    autoGenerated = viaYtDlp.autoGenerated;
  } catch (err) {
    if (err instanceof YtDlpMissingError) {
      throw new TranscriptError(err.message, "no_ytdlp");
    }
    // Direct read as a last resort. It returns nothing today, but costs one
    // request and starts working again the moment YouTube relaxes this.
    const xml = await fetchText(track.url, timeoutMs);
    segments = parseTimedText(xml);
    if (segments.length === 0) {
      const message = err instanceof Error ? err.message : "Could not download the caption track.";
      // yt-dlp names YouTube's 429 in its message, and it is the same wait as the one above.
      throw new TranscriptError(message, /\b429\b/.test(message) ? "rate_limited" : "blocked");
    }
  }

  if (segments.length === 0) {
    throw new TranscriptError("The caption track was empty.", "no_captions");
  }

  return { videoId, language, autoGenerated, segments };
}

/** `1h02m03s` style stamps read better than raw seconds in a transcript dump. */
export function formatTimestamp(seconds: number): string {
  const total = Math.floor(seconds);
  const h = Math.floor(total / 3600);
  const m = Math.floor((total % 3600) / 60);
  const s = total % 60;
  const pad = (n: number) => String(n).padStart(2, "0");
  return h > 0 ? `${h}:${pad(m)}:${pad(s)}` : `${m}:${pad(s)}`;
}

/** Collapse segments into readable prose. Auto-captions arrive as ~2 second fragments. */
export function toPlainText(segments: TranscriptSegment[]): string {
  return segments
    .map((s) => s.text)
    .join(" ")
    .replace(/\s+/g, " ")
    .trim();
}

/** Timestamped lines, grouped so the output is scannable rather than one line per fragment. */
export function toTimestampedText(segments: TranscriptSegment[], groupSeconds = 30): string {
  const lines: string[] = [];
  let bucketStart: number | null = null;
  let buffer: string[] = [];

  const flush = () => {
    if (bucketStart !== null && buffer.length) {
      lines.push(`[${formatTimestamp(bucketStart)}] ${buffer.join(" ").replace(/\s+/g, " ").trim()}`);
    }
    buffer = [];
  };

  for (const seg of segments) {
    if (bucketStart === null) bucketStart = seg.start;
    if (seg.start - bucketStart >= groupSeconds) {
      flush();
      bucketStart = seg.start;
    }
    buffer.push(seg.text);
  }
  flush();
  return lines.join("\n");
}

/** Find a phrase in a transcript and return the timestamps where it occurs. */
export function searchSegments(
  segments: TranscriptSegment[],
  query: string,
  contextSegments = 1,
): { timestamp: string; start: number; text: string }[] {
  const needle = query.toLowerCase().trim();
  if (!needle) return [];
  const hits: { timestamp: string; start: number; text: string }[] = [];

  for (let i = 0; i < segments.length; i++) {
    const seg = segments[i];
    if (!seg || !seg.text.toLowerCase().includes(needle)) continue;
    const from = Math.max(0, i - contextSegments);
    const to = Math.min(segments.length, i + contextSegments + 1);
    const text = segments
      .slice(from, to)
      .map((s) => s.text)
      .join(" ")
      .replace(/\s+/g, " ")
      .trim();
    hits.push({ timestamp: formatTimestamp(seg.start), start: seg.start, text });
  }
  return hits;
}
