/**
 * yt-dlp transport for caption tracks.
 *
 * As of 2026 YouTube answers a bare `timedtext` URL with 200 and an empty body
 * unless the request carries a proof-of-origin token tied to a real player
 * session. Scraping the watch page still lists which tracks exist, but it can
 * no longer read their contents, so the track list and the track body now come
 * from different places.
 *
 * yt-dlp already solves the hard half and is maintained against YouTube's
 * changes far faster than this repo could be, so we shell out to it rather than
 * reimplement token minting. It is an optional dependency: without it you can
 * still list languages, and every other tool in this server is unaffected.
 */

import { spawn } from "node:child_process";
import { mkdtemp, readdir, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import type { TranscriptSegment } from "./transcripts.js";

const BINARY = process.env.YOUTUBE_YTDLP_PATH?.trim() || "yt-dlp";

export class YtDlpMissingError extends Error {
  constructor() {
    super(
      "yt-dlp is not installed. Transcripts need it because YouTube no longer serves caption text directly. Install it with `brew install yt-dlp` (macOS) or `pipx install yt-dlp`, or set YOUTUBE_YTDLP_PATH to its location.",
    );
    this.name = "YtDlpMissingError";
  }
}

function run(args: string[], timeoutMs: number): Promise<{ code: number; stdout: string; stderr: string }> {
  return new Promise((resolve, reject) => {
    const child = spawn(BINARY, args, { stdio: ["ignore", "pipe", "pipe"] });
    let stdout = "";
    let stderr = "";
    const timer = setTimeout(() => {
      child.kill("SIGKILL");
      reject(new Error(`yt-dlp timed out after ${timeoutMs}ms`));
    }, timeoutMs);

    child.stdout.on("data", (d: Buffer) => (stdout += d.toString()));
    child.stderr.on("data", (d: Buffer) => (stderr += d.toString()));
    child.on("error", (err: NodeJS.ErrnoException) => {
      clearTimeout(timer);
      if (err.code === "ENOENT") reject(new YtDlpMissingError());
      else reject(err);
    });
    child.on("close", (code) => {
      clearTimeout(timer);
      resolve({ code: code ?? 1, stdout, stderr });
    });
  });
}

/** True when yt-dlp can actually be launched. Used by `doctor` and by tool errors. */
export async function isAvailable(): Promise<boolean> {
  try {
    const { code } = await run(["--version"], 10000);
    return code === 0;
  } catch {
    return false;
  }
}

/** `en-orig` and `en-en` both just mean `en`. */
function normalizeLang(code: string): string {
  const bare = code.replace(/-orig$/, "");
  const halves = bare.split("-");
  if (halves.length === 2 && halves[0] && halves[0].toLowerCase() === halves[1]?.toLowerCase()) {
    return halves[0];
  }
  return bare;
}

type Json3 = {
  events?: { tStartMs?: number; dDurationMs?: number; segs?: { utf8?: string }[] }[];
};

function parseJson3(raw: string): TranscriptSegment[] {
  const doc = JSON.parse(raw) as Json3;
  const out: TranscriptSegment[] = [];
  for (const ev of doc.events ?? []) {
    const text = (ev.segs ?? [])
      .map((s) => s.utf8 ?? "")
      .join("")
      .replace(/\s+/g, " ")
      .trim();
    // Auto-caption streams include empty timing events used for on-screen
    // positioning. They carry no words and would show up as blank lines.
    if (!text) continue;
    out.push({
      start: (ev.tStartMs ?? 0) / 1000,
      duration: (ev.dDurationMs ?? 0) / 1000,
      text,
    });
  }
  return out;
}

export type YtDlpTranscript = {
  segments: TranscriptSegment[];
  /** The language actually written out, which may be a regional variant of what was asked for. */
  language: string;
  autoGenerated: boolean;
};

/**
 * Download one caption track.
 *
 * `--sub-langs` accepts a glob, so `en.*` picks up `en`, `en-GB` and the
 * auto-generated `en-orig` in one pass. We take whichever file lands and report
 * the language from its name rather than assuming we got the exact code asked
 * for.
 */
export async function fetchCaptions(
  videoId: string,
  language = "en",
  timeoutMs = 90000,
): Promise<YtDlpTranscript> {
  const dir = await mkdtemp(join(tmpdir(), "youtube-mcp-"));
  try {
    const lang = language.includes("*") ? language : `${language}.*`;
    const { code, stderr } = await run(
      [
        "--skip-download",
        "--write-subs",
        "--write-auto-subs",
        "--sub-langs",
        lang,
        "--sub-format",
        "json3",
        "--no-warnings",
        "--no-playlist",
        // The bot check's own error names this setting: a cookies.txt exported from a signed-in browser.
        ...(process.env.YOUTUBE_YTDLP_COOKIES?.trim() ? ["--cookies", process.env.YOUTUBE_YTDLP_COOKIES.trim()] : []),
        "-o",
        join(dir, "cap"),
        `https://www.youtube.com/watch?v=${videoId}`,
      ],
      timeoutMs,
    );

    const files = (await readdir(dir)).filter((f) => f.endsWith(".json3"));
    if (files.length === 0) {
      if (/HTTP Error 429|Too Many Requests/i.test(stderr)) {
        throw new Error(
          "YouTube is rate limiting this IP (HTTP 429). Wait a few minutes before retrying, or run with a proxy.",
        );
      }
      if (/Sign in to confirm|bot/i.test(stderr)) {
        throw new Error(
          "YouTube asked yt-dlp to prove it is not a bot. Set YOUTUBE_YTDLP_COOKIES to a cookies.txt exported from a browser signed in to YouTube, or retry later.",
        );
      }
      throw new Error(
        code === 0
          ? "No captions were downloaded. The video probably has none in that language."
          : `yt-dlp failed: ${stderr.trim().split("\n").pop() ?? "unknown error"}`,
      );
    }

    // Prefer a human-written track over the auto one when both arrive. yt-dlp
    // names auto-generated files `<id>.<lang>-orig.json3`.
    const chosen = files.find((f) => !f.includes("-orig.")) ?? files[0]!;
    const raw = await readFile(join(dir, chosen), "utf8");
    const matched = /\.([A-Za-z0-9-]+)\.json3$/.exec(chosen);

    return {
      segments: parseJson3(raw),
      // yt-dlp writes variant tracks as `<lang>-<lang>` (e.g. `en-en`) and its
      // auto track as `<lang>-orig`. Both mean the plain language to a caller.
      language: normalizeLang(matched?.[1] ?? language),
      autoGenerated: chosen.includes("-orig."),
    };
  } finally {
    await rm(dir, { recursive: true, force: true });
  }
}
