/**
 * Transcript tools.
 *
 * These are the only tools that work with no credentials of any kind, and they
 * read anyone's video rather than only your own. For most people this is the
 * reason to install the server at all, so it is the group listed first.
 */

import { z } from "zod";
import {
  fetchTranscript,
  listTracks,
  parseVideoId,
  searchSegments,
  toPlainText,
  toTimestampedText,
} from "../youtube/transcripts.js";
import { defineTool, type AnyToolSpec } from "./kit.js";

const video = z
  .string()
  .describe("Video id or any YouTube URL: watch, youtu.be, Shorts, embed or live.");

export const transcriptTools: AnyToolSpec[] = [
  defineTool({
    name: "get_transcript",
    title: "Get transcript",
    description:
      "Read the transcript of ANY public YouTube video, not just your own. Needs no API key, no connected account and no quota. Returns prose by default, or timestamped lines when you need to cite a moment. Videos with captions disabled have no transcript and nothing can recover one.",
    schema: {
      video,
      language: z
        .string()
        .optional()
        .describe("Language code such as `en`, `es`, `de`. Defaults to English, then whatever exists."),
      timestamps: z
        .boolean()
        .optional()
        .describe("Return `[m:ss] text` lines instead of prose. Use when you need to point at a moment."),
      group_seconds: z
        .number()
        .min(5)
        .max(300)
        .optional()
        .describe("Seconds of speech per timestamped line. Default 30."),
    },
    risk: "read",
    handler: async ({ video: v, language, timestamps, group_seconds }, ctx) => {
      const t = await fetchTranscript(v, { language: language ?? ctx.config.defaultLanguage });
      const body = timestamps
        ? toTimestampedText(t.segments, group_seconds ?? 30)
        : toPlainText(t.segments);
      return (
        `video: ${t.videoId}\nlanguage: ${t.language}${t.autoGenerated ? " (auto-generated)" : ""}\n` +
        `segments: ${t.segments.length}\n\n${body}`
      );
    },
  }),

  defineTool({
    name: "list_transcript_languages",
    title: "List transcript languages",
    description:
      "List every caption language on a video and whether each was written by a human or auto-generated. Human captions are more accurate. Call this before get_transcript when the video may not be in English.",
    schema: { video },
    risk: "read",
    handler: async ({ video: v }) => {
      const id = parseVideoId(v);
      if (!id) throw new Error(`Could not read a video id out of "${v}".`);
      const tracks = await listTracks(id);
      if (tracks.length === 0) return "This video has no captions.";
      return tracks
        .map((t) => `${t.languageCode}\t${t.languageName}${t.autoGenerated ? "\t(auto-generated)" : ""}`)
        .join("\n");
    },
  }),

  defineTool({
    name: "search_transcript",
    title: "Search inside a video",
    description:
      "Find every place a phrase is said in a video and get the timestamps, each as a link that jumps to that second. Use this instead of pulling a whole transcript when you only need to locate something.",
    schema: {
      video,
      query: z.string().min(1).describe("The phrase to find. Case-insensitive substring match."),
      language: z.string().optional(),
      context_segments: z
        .number()
        .min(0)
        .max(5)
        .optional()
        .describe("Caption segments either side to include for context. Default 1."),
    },
    risk: "read",
    handler: async ({ video: v, query, language, context_segments }, ctx) => {
      const t = await fetchTranscript(v, { language: language ?? ctx.config.defaultLanguage });
      const hits = searchSegments(t.segments, query, context_segments ?? 1);
      if (hits.length === 0) return `"${query}" is not said in this video.`;
      const body = hits
        .map((h) => `[${h.timestamp}] https://youtu.be/${t.videoId}?t=${Math.floor(h.start)}\n${h.text}`)
        .join("\n\n");
      return `${hits.length} match(es)\n\n${body}`;
    },
  }),

  defineTool({
    name: "get_transcripts",
    title: "Get several transcripts",
    description:
      "Fetch transcripts for up to 20 videos in one call. A video with no captions is reported in place rather than failing the batch. Use it to compare how a set of videos open, or to build a corpus before analyzing it.",
    schema: {
      videos: z.array(video).min(1).max(20).describe("Up to 20 video ids or URLs."),
      language: z.string().optional(),
      max_chars_each: z
        .number()
        .min(200)
        .optional()
        .describe("Truncate each transcript to this many characters. Useful when you only need the openings."),
    },
    risk: "read",
    handler: async ({ videos, language, max_chars_each }, ctx) => {
      const parts: string[] = [];
      for (const v of videos) {
        try {
          const t = await fetchTranscript(v, { language: language ?? ctx.config.defaultLanguage });
          let text = toPlainText(t.segments);
          if (max_chars_each && text.length > max_chars_each) text = `${text.slice(0, max_chars_each)}…`;
          parts.push(`### ${t.videoId} (${t.language})\n${text}`);
        } catch (err) {
          parts.push(`### ${v}\nNo transcript: ${err instanceof Error ? err.message : String(err)}`);
        }
      }
      return parts.join("\n\n");
    },
  }),
].map((t) => t as AnyToolSpec);
